spring.application.name=WorkHistory
server.port:8083
spring.datasource.url=jdbc:mysql://localhost:3306/workhistory
spring.datasource.username=root
spring.datasource.password=Saikiran@123

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=sai
spring.security.user.password=sai

jwt.key=nK7mX2pQ9vL4sR8tY6wE3cA1uF5hJ0zBqD7xM9sV2kP8rT4yN6gH3fW1cZ5aL9uQ